TARGET = libyajl
DLLIB = $(TARGET).bundle
all:

install:
	mkdir -p /Users/kyaukyuai/serverspec-test/.vendor/ruby/2.1.0/gems/libyajl2-1.1.0/lib/libyajl2/vendored-libyajl2/lib
	cp $(DLLIB) /Users/kyaukyuai/serverspec-test/.vendor/ruby/2.1.0/gems/libyajl2-1.1.0/lib/libyajl2/vendored-libyajl2/lib/$(DLLIB)
	mkdir -p /Users/kyaukyuai/serverspec-test/.vendor/ruby/2.1.0/gems/libyajl2-1.1.0/lib/libyajl2/vendored-libyajl2/include/yajl
	cp yajl/*.h /Users/kyaukyuai/serverspec-test/.vendor/ruby/2.1.0/gems/libyajl2-1.1.0/lib/libyajl2/vendored-libyajl2/include/yajl
